language: php

php:
  - '7.3'
  - '7.2'
#- '7.1'
#- '7.0'
#- '5.6'
#- '5.5'
#- '5.4'

install: composer update

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - bash <(curl -s https://codecov.io/bash) -c -F unittests_phpunit -X fix
  - vendor/bin/codecept run unit --coverage-xml=../../coverage.xml
  - vendor/bin/infection --threads=$(nproc) --min-covered-msi=60 --min-msi=30
  - bash <(curl -s https://codecov.io/bash) -c -F unittests_codeception -X fix

env:
  global:
    secure: qXhN1BanuFrdtm/TCRPR/J7hweOZZFLQZUUOYBgfdMoQexHkPENkLWwmrTfb6noSxK1cf6m03WjdtmflSkjm/QWzC4wqSnTgpRP/XlSJ2hb/0rqdRI+7RWpwWzjTigukjPWDERR5JA05hDT8TsSu/bjs53L+uKOe+/IBEHhbKlaugovKMIvbQTxOnoqCWsm9G2MCJCFWlMZNgubAIfkhckmqg948l6i+RO2J06XT3vFQlytdFL3unls3aSHjuCEwoWx+j3Mdj6FhL8o2Pm/kIhOwMcsjESCOWsadZZvB+E1+c9NLkkIj9qooFh8OAnLqkLhCKNzNpMD9pSoJO4xi+3oKi7/k9Dho3or+TYm4muAZK3bXHvgr1XnQUTKyH0hKttDaxPxs9c4HIKCwwqt/koGQFDQ5/0GIGyvrWviX4sQFgGwgBsLoiB77PZmDycr0EtpMeVnjSIMRLoiKPqsGEgRDQkbrHhReMG1VwXc8kkK5ILupEpCwbuvdDiUQC4cvCbkt0Sx8j4+mTFBXH9pO7nMVuncnv+NMTVXLBKBGBgDAc0+Pu/JdB1KiJZbkZr1yeat1RIkSRWAIaNFR6mjKTPwGA85b18oG0YP+HlQhzrFW+rWbYbHDHemwnAYYvbRFMLXrYNeOh4VNS7ub6xQ6/CWS3mMsdd6yJY1D5STUG2E=
