coverage:
  status:
    project:
      default:
        target: 100%
        threshold: null
      unittests_codeception:
        flags: unittests_codeception
        target: 66%
      unittests_phpunit:
        flags: unittests_phpunit
        target: 60%
flags:
  unittests_codeception:
    paths:
      - src/
  unittests_phpunit:
    paths:
      - src/
